### ISSUE TITLE
[BUG] envycontrol not working at all

### ISSUE THREAD

**Issue by arnavgr** [bayasdev/envycontrol#102]
**Describe the bug**
Changing modes in envycontrol do nothing. they show no error, but upon restart even though --query shows integrated it always runs on hybrid default. i have my second monitor connected with my laptop but even when it is disconnected it doesnt work.

**Expected behavior**
sudo envycontrol -s integrated works without error. upon reboot my second monitor connected through hdmi works(which it shouldnt)
nvidia-smi and nvidia-settings both show my graphics card  [GeForce MX150].  switching to hybrid or nvidia mode chnages nothing.

journalctl | grep nvidia : https://pastebin.com/mqfRT7mc

**System Information:**
 - Model: Asus Vivobook X510UNR
 - Distro: [Arch]
 - Kernel: 6.3.1-arch1-1
 - DE/WM and Display Manager (if applicable): Hyprland and no DM
 - EnvyControl version: 3.2.0-2
 - Nvidia driver version: 530.41.03
 - lspci output:
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 08)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1e.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO UART Controller #0 (rev 21)
00:1e.2 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO SPI Controller #0 (rev 21)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point LPC Controller/eSPI Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX150] (rev a1)
02:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
```

**Comment by luigi370** [comment]
Yeap.. same issue here. May be is related to python. Many of my apps depending on python packages where not working untill I re-installed. envyControl as well.. however, even after re-install, envycontrol dont show any errors but dont really work.

**Comment by NoahFraiture** [comment]
Hello, is there any advance ? I also use hyprland and it doesn't seem to work

**Comment by arnavgr** [comment]
> Hello, is there any advance ? I also use hyprland and it doesn't seem to work

I switched to gdm and removed nvidia.drm=1 from my kernel parameter and it started working. Also my second monitor can't be used without enabling my dGPU so I removed it
