### ISSUE TITLE
[REQUEST] add option to disable NVreg_PreserveVideoMemoryAllocations

### ISSUE THREAD

**Issue by everyx** [bayasdev/envycontrol#105]
**Is your feature request related to a problem? Please describe.**
NVIDIA driver is buggy with hibernation (Arch Linux + Gnome + Wayland),  It would be nice to be able to provide an option to set `NVreg_PreserveVideoMemoryAllocations=0`,  which will brings hibernation back to work on my computer.

Although this will make GDM's Wayland session option disappear, but we can have other ways to enable it, at least this makes hibernation work.

**Describe the solution you'd like**
Add a option like `envycontrol -s hybrid --disalbe-preserve-video-memory-allocations`

**Comment by Boria138** [comment]
> **Is your feature request related to a problem? Please describe.**
> NVIDIA driver is buggy with hibernation (Arch Linux + Gnome + Wayland),  It would be nice to be able to provide an option to set `NVreg_PreserveVideoMemoryAllocations=0`,  which will brings hibernation back to work on my computer.
> 
> Although this will make GDM's Wayland session option disappear, but we can have other ways to enable it, at least this makes hibernation work.
> 
> **Describe the solution you'd like**
> Add a option like `envycontrol -s hybrid --disalbe-preserve-video-memory-allocations`
> 

That can be closed since NVreg_PreserveVideoMemoryAllocations is now disabled by default, and for all those who need Wayland it is written how to enable it with disabled NVreg_PreserveVideoMemoryAllocations.
