### ISSUE TITLE
[BUG] /lib/udev/rules.d/80-nvidia-pm.rules disables rtd3 power control

### ISSUE THREAD

**Issue by cemkaya-mpi** [bayasdev/envycontrol#106]
**Describe the bug**
The file /lib/udev/rules.d/80-nvidia-pm.rules results in no rtd3 power control on my laptop with RTX3060 and Ryzen 6800H.

**To Reproduce**
1. Run `sudo envycontrol -s hybrid --rtd3 3 --reset-sddm --verbose`
2. See that the GPU never powers off

**Expected behavior**
The discrete GPU should power off when not used.

**System Information:**
 - Model: [Dell G15 5525]
 - Distro: [Arch Linux]
 - Kernel: [6.2.12]
 - DE/WM and Display Manager (if applicable): [KDE Plasma with SDDM]
 - EnvyControl version: [e.g. 3.2.0]
 - Nvidia driver version: [525.89.02-1]

**Additional context**
After removing the file, rtd3 works again.

**Comment by bayasdev** [comment]
Interesting results, does it work without the --rtd-3 flag?

**Comment by cemkaya-mpi** [comment]
Without the flag, power saving works as intended.
```
cat /proc/driver/nvidia/gpus/0000:01:00.0/power                                                                         ✔ 
Runtime D3 status:          Enabled (fine-grained)
Video Memory:               Off

GPU Hardware Support:
 Video Memory Self Refresh: Supported
 Video Memory Off:          Supported
```

**Comment by cemkaya-mpi** [comment]
Should I close this issue, as removing the --rtd3 flag solves the problem?
