### ISSUE TITLE
[QUESTION] how to set applications/games to launch with the nvidia gpu in hybrid mode

### ISSUE THREAD

**Issue by revolutton** [bayasdev/envycontrol#130]
What are the best ways to get my applications/games to use my nvidia card in hybrid mode? Running steam games with the nvidia gpu in hybrid mode should I always set the launch options to (DRI_PRIME=1 <command> ) for nouveau and (__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia <command> ) for the propietary driver or will (prime-run %command%) still work? Im also guessing the same will go for configuring software shortcuts to launch with the nvidia gpu.

**Comment by bayasdev** [comment]
You can use prime-run ;)
