### ISSUE TITLE
[BUG] HP victus 15 fa-0xxx can't wake-up from suspend when on hybrid mode.

### ISSUE THREAD

**Issue by Pherrara** [bayasdev/envycontrol#162]
**Describe the bug**
When I'm in hybrid mode, and I suspend my laptop with:
 ```
systemctl suspend
``` 
I can't wake it up: first the screen goes black, then black-dimmed, then some errors show up, I'm gonna attach a photo of the errors.
Then the displaymanager (SDDM) pops up but with 0 FPS, if I type the password and enter, after some time PC wakes up but still with 0 FPS.
Only fix at this point it to hold down power button and restart.
The problem is not present if I'm in integrated mode: suspend works as intended.

**To Reproduce**
1. Run `sudo envycontrol -s hybrid && reboot`
2. Run 'systemctl suspend'

**Expected behavior**
PC to wake up from suspend while in hybrid mode.

**Screenshots**
I'm gonna attach a screenshot of the errors after I try to wake up the PC from suspend.
![IMG_20240405_220324](https://github.com/bayasdev/envycontrol/assets/48262871/581ee178-97a7-4d42-8042-332d04551f06)

**System Information:**
 - Model: HP VICTUS 15 fa-0xxx, i7 12700h, RTX 3050Ti 4GB
 - Distro: EndeavourOS (rolling release)
 - Kernel: 6.8.2-arch2-1
 - DE/WM and Display Manager (if applicable): KDE Plasma 6.0.3 (WAYLAND) with SDDM
 - EnvyControl version: 3.4.0
 - Nvidia driver version: 
```
lib32-nvidia-utils 550.67-1
nvidia-dkms 550.67-1
nvidia-hook 1.5-2
nvidia-inst 24-1
nvidia-settings 550.67-1
nvidia-utils 550.67-1
```
 - lspci output:
```
00:00.0 Host bridge: Intel Corporation 12th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:01.0 PCI bridge: Intel Corporation 12th Gen Core Processor PCI Express x16 Controller #1 (rev 02)
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] (rev 0c)
00:04.0 Signal processing controller: Intel Corporation Alder Lake Innovation Platform Framework Processor Participant (rev 02)
00:06.0 PCI bridge: Intel Corporation 12th Gen Core Processor PCI Express x4 Controller #0 (rev 02)
00:08.0 System peripheral: Intel Corporation 12th Gen Core Processor Gaussian & Neural Accelerator (rev 02)
00:0d.0 USB controller: Intel Corporation Alder Lake-P Thunderbolt 4 USB Controller (rev 02)
00:14.0 USB controller: Intel Corporation Alder Lake PCH USB 3.2 xHCI Host Controller (rev 01)
00:14.2 RAM memory: Intel Corporation Alder Lake PCH Shared SRAM (rev 01)
00:15.0 Serial bus controller: Intel Corporation Alder Lake PCH Serial IO I2C Controller #0 (rev 01)
00:16.0 Communication controller: Intel Corporation Alder Lake PCH HECI Controller (rev 01)
00:1c.0 PCI bridge: Intel Corporation Device 51bc (rev 01)
00:1c.6 PCI bridge: Intel Corporation Device 51be (rev 01)
00:1c.7 PCI bridge: Intel Corporation Alder Lake PCH-P PCI Express Root Port #9 (rev 01)
00:1f.0 ISA bridge: Intel Corporation Alder Lake PCH eSPI Controller (rev 01)
00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
00:1f.4 SMBus: Intel Corporation Alder Lake PCH-P SMBus Host Controller (rev 01)
00:1f.5 Serial bus controller: Intel Corporation Alder Lake-P PCH SPI Controller (rev 01)
02:00.0 Non-Volatile memory controller: Sandisk Corp WD PC SN810 / Black SN850 NVMe SSD (rev 01)
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device 5228 (rev 01)
04:00.0 Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter
05:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller (rev 16)
```

**Comment by klmcwhirter** [comment]
@Pherrara it looks like your lspci output was captured in integrated mode. I do not see the nvidia devices.

Performing `envycontrol --reset` should put your laptop back in hybrid mode. Do you see a difference in the behavior?

Please note that there was no functional difference in 3.4.0 other than caching the nvidia pci bus id so that a transition from integrated to nvidia mode was possible.
_Please see #155 and /var/cache/envycontrol/cache.json _

Can you please confirm whether or not the behavior exists in the previous version?

**Comment by Pherrara** [comment]
Yeah sorry, here's the ```lspci``` output while in hybrid mode:
```
00:00.0 Host bridge: Intel Corporation 12th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:01.0 PCI bridge: Intel Corporation 12th Gen Core Processor PCI Express x16 Controller #1 (rev 02)
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] (rev 0c)
00:04.0 Signal processing controller: Intel Corporation Alder Lake Innovation Platform Framework Processor Participant (rev 02)
00:06.0 PCI bridge: Intel Corporation 12th Gen Core Processor PCI Express x4 Controller #0 (rev 02)
00:08.0 System peripheral: Intel Corporation 12th Gen Core Processor Gaussian & Neural Accelerator (rev 02)
00:0d.0 USB controller: Intel Corporation Alder Lake-P Thunderbolt 4 USB Controller (rev 02)
00:14.0 USB controller: Intel Corporation Alder Lake PCH USB 3.2 xHCI Host Controller (rev 01)
00:14.2 RAM memory: Intel Corporation Alder Lake PCH Shared SRAM (rev 01)
00:15.0 Serial bus controller: Intel Corporation Alder Lake PCH Serial IO I2C Controller #0 (rev 01)
00:16.0 Communication controller: Intel Corporation Alder Lake PCH HECI Controller (rev 01)
00:1c.0 PCI bridge: Intel Corporation Device 51bc (rev 01)
00:1c.6 PCI bridge: Intel Corporation Device 51be (rev 01)
00:1c.7 PCI bridge: Intel Corporation Alder Lake PCH-P PCI Express Root Port #9 (rev 01)
00:1f.0 ISA bridge: Intel Corporation Alder Lake PCH eSPI Controller (rev 01)
00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
00:1f.4 SMBus: Intel Corporation Alder Lake PCH-P SMBus Host Controller (rev 01)
00:1f.5 Serial bus controller: Intel Corporation Alder Lake-P PCH SPI Controller (rev 01)
01:00.0 VGA compatible controller: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 2291 (rev a1)
02:00.0 Non-Volatile memory controller: Sandisk Corp WD PC SN810 / Black SN850 NVMe SSD (rev 01)
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device 5228 (rev 01)
04:00.0 Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter
05:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller (rev 16)
```

I just tried envycontrol version 3.3.1 with ```envycontrol --reset``` and the problem persists. I then checked on ```/var/cache/envycontrol/cache.json``` and I have no file there.

Also: I noticed in the last few days that I get more battery life on hybrid and nvidia mode than in integrated... (hybrid and nvidia battery drain is basically the same) so I think there's something wrong with how power management is integrated.
I also tried to manually enable those services while in nvidia/hybrid mode:
```
sudo systemctl enable nvidia-suspend.service
sudo systemctl enable nvidia-hibernate.service
sudo systemctl enable nvidia-resume.service
```
But nothing worked so far.

**Comment by bayasdev** [comment]
@Pherrara this sounds like a Nvidia driver bug.

**Comment by klmcwhirter** [comment]
@Pherrara the cache file was added in version 3.4.0 - it was the main feature. So, no, it did not exist in  version 3.3.1.

But the important bit of info is that the issue you are having exists with 3.3.1. When you did the --reset you effectively put things back the way they were before you used envycontrol - i.e., hybrid mode.

So because the problem still exists, I agree with @bayasdev. The issue must be with the driver and/or the way it installs itself with the distro you are using.

I do not think we should treat this as an envycontrol bug.

**Comment by bayasdev** [comment]
> @Pherrara the cache file was added in version 3.4.0 - it was added to support the main feature of that release. So, no, it did not exist in  version 3.3.1.
> 
> 
> 
> But the important bit of info is that the issue you are having exists with 3.3.1. When you did the --reset you effectively put things back the way they were before you used envycontrol - i.e., hybrid mode.
> 
> 
> 
> So because the problem still exists, I agree with @bayasdev. The issue must be with the driver and/or the way it installs itself with the distro you are using.
> 
> 
> 
> I do not think we should treat this as an envycontrol bug.

Yup, closing this for now
