### ISSUE TITLE
[Wiki Update] Add Void Linux to tested-distros list

### ISSUE THREAD

**Issue by yenurbek** [bayasdev/envycontrol#163]
Works well on Void Linux (bspwm, dwm), but adding the blacklisting of nouveau is required. 

/etc/modprobe.d/nouveau.conf

`blacklist nouveau`

**Comment by yenurbek** [comment]
You may need to blacklist NVIDIA drivers except the proprietary driver.  Depends on complaints in x11 logs

**Comment by klmcwhirter** [comment]
What works or doesn't work requiring the blacklist?

envycontrol is doing that.

Please see https://github.com/bayasdev/envycontrol/blob/main/envycontrol.py#L21

Also note that testing all Linux distros is not practical at this time. But perhaps with your help we can address your issue.

Thanks.

**Comment by bayasdev** [comment]
PTAL @yenurbek just updated the wiki
https://github.com/bayasdev/envycontrol/wiki/Frequently-Asked-Questions#tested-distros

Regarding blacklisting nouveau this is already handled by EnvyControl.

**Comment by yenurbek** [comment]
I noticed that envycontrol doesn't generate
/etc/modprobe.d/blacklist-nvidia.conf.
I am using 3.2.0 version of envycontrol, maybe it is crucial.

@klmcwhirter approach you mentioned looks really interesting, i will try it but later because of time.

**Comment by bayasdev** [comment]
> Blacklisting nouveau is required when switching to nvidia mode, otherwise xorg session is not starting

Then your distro got its Nvidia packaging wrong, each distro I've tested automatically blacklists nouveau when the user installs the proprietary driver.

**Comment by yenurbek** [comment]
I think you are right

According to
https://github.com/void-linux/void-packages/blob/master/srcpkgs%2Fnvidia%2Ftemplate#L263 
nvidia package creates the blacklist file in /usr/lib/modprobe.d where it has no effect on the system

**Comment by bayasdev** [comment]
> I think you are right
> 
> According to
> https://github.com/void-linux/void-packages/blob/master/srcpkgs%2Fnvidia%2Ftemplate#L263 
> nvidia package creates the blacklist file in /usr/lib/modprobe.d where it has no effect on the system
> 
> 

You should open an issue downstream

**Comment by bayasdev** [comment]
Closing this as of now
