### ISSUE TITLE
[FILE ISN'T DOWNLOADING]

### ISSUE THREAD

**Issue by Kavya879** [bayasdev/envycontrol#164]
I am currently using Ubuntu on my laptop . I followed all the instructions mentioned but the problem is that once i download the file and write the command  "sudo apt -y install ./python3-envycontrol_3.4.0.deb" , it is showing such command doesn't exist which shouldn't be the case  . What can i do to fix this issue?

**Comment by bayasdev** [comment]
Have you downloaded the file? dpkg -i my.deb

**Comment by Shelonlovesanime** [comment]
Yes i did , Although it works now in the terminal after cloning the git repo .

**Comment by Kavya879** [comment]
Yes , i did but now it works in the terminal after cloning the git repo
