### ISSUE TITLE
hi please help mi out to figure this

### ISSUE THREAD

**Issue by nmars-cloud** [bayasdev/envycontrol#17]
im using vanilla arch mate desktop when i switch to nvidia i cant login hybrid mode works on cinamon hovewer work both same situation on optimus please help thank you

**Comment by nmars-cloud** [comment]
my journal Process 7699 (Xorg) of user 0 dumped core.
                                                      
                                                      Module linux-vdso.so.1 with build-id c383727bad7b2b0dc9d2be991ee2f300d229360a
                                                      Module libgobject-2.0.so.0 with build-id e67b3a29cecdd98c3d8bd6eb7524a812331b20a2
                                                      Module libgudev-1.0.so.0 with build-id a9f734ea9206d637d5aacfbd86298c91cdc1a33a
                                                      Module libwacom.so.9 with build-id 7e303135e132c1d883060092e9b4cc5971a94378
                                                      Module libevdev.so.2 with build-id b62ae69f839f1b6b06ef2c1df19f25ff09b0d824
                                                      Module libmtdev.so.1 with build-id 0cea2a842ae9a0ef02a08477076caab0e5ac5e42
                                                      Module libinput.so.10 with build-id 956df35c2a15681d4aa87253ed15a5c18a339183
                                                      Module libinput_drv.so with build-id cf829f2000cbe7c7b226d0bc4c8188ab0fa99b62
                                                      Module libxcb-sync.so.1 with build-id dda14591103b01b1311906053bf1ca9e82ade35c
                                                      Module libxcb-present.so.0 with build-id 68f5465258750e2397b1333b3ffc01ee33caa4e1
                                                      Module libxcb-dri3.so.0 with build-id 9407a2480e09dc5a1dd9d9a0652fa8d32b328c91
                                                      Module libxcb-xfixes.so.0 with build-id a6b197ace5b9b59f913f5969eb419a88d1194f47
                                                      Module libxcb-dri2.so.0 with build-id 2dd6e65129a809dab828a1d26215a3f7a363fcc8
                                                      Module libX11-xcb.so.1 with build-id 0db4f94d8ae31b8dc9a83f825a9171656f1e532c
                                                      Module libEGL_mesa.so.0 with build-id 87783c9234dbd9030a4c7c71387b75ab04c03ed9
                                                      Module libnvidia-egl-gbm.so.1 with build-id e0818354660c8a99ce2f72bda50cf4a2eae7bd7d
                                                      Module libnvidia-eglcore.so.510.47.03 with build-id dd2a471b7a7acbc5b02ebce3271a8a7e5c57bb29
                                                      Module libwayland-client.so.0 with build-id 0a237f2fd096bada4ca381eec5d64474c4078be4
                                                      Module libnvidia-egl-wayland.so.1 with build-id 7026a2a5082aff391d23ed5af4678c543383f2d9
                                                      Module libnvidia-glsi.so.510.47.03 with build-id 495215b6646c229e97412d5e37067e365d9072b1
                                                      Module libEGL_nvidia.so.0 with build-id 00c57addfc44db8179398fb3b940fe7954490299
                                                      Module libEGL.so.1 with build-id 686c2e4036c01a3a72349ed0dd04f7c434af14ce
                                                      Module libnss_files.so.2 with build-id 1a36dfc01d3a1010b2ee79766a24a8090a3266d5
                                                      Module libicudata.so.70 with build-id e1dcc2a88cfaafed882d09c90c668af0eed4efed
                                                      Module libicuuc.so.70 with build-id 2e245c2bf12f95fd8ab79b3a4be99524677cbd70
                                                      Module libxml2.so.2 with build-id b710b880b0d4e9c93554fa632129db44c20632cd
                                                      Module libncursesw.so.6 with build-id 1f873ddb2c32ab39d0b7d8646d03680ffe99de7c
                                                      Module libedit.so.0 with build-id 4b0babfcad161c2ad0af6e59e2493258db23a331
                                                      Module libvulkan.so.1 with build-id 40c7a455d37803dbd362377df831a77142acb66b
                                                      Module libdrm_nouveau.so.2 with build-id ee16fa6a4d0bd08f5448cfc046ccb76b49aaa8a3
                                                      Module libdrm_amdgpu.so.1 with build-id 30d019987d514b23115b47d6b47c1e45c18fdbaf
                                                      Module libelf.so.1 with build-id 0eee16e5e39ae4c5016f31b2abb6c92f0804ae47
                                                      Module libdrm_radeon.so.1 with build-id 5d1615e0467d0a34a5a82cbd4ebc84851e116307
                                                      Module libsensors.so.5 with build-id dc8b2c1c0d8525411aca188ea3cc3fb86d381d30
                                                      Module libLLVM-13.so with build-id 62bb83aeee3a955305312248a401be2cf62a0ea8
                                                      Module radeonsi_dri.so with build-id 10a9eafed46383cccd7c3dc76676aa5fdd37f3e5
                                                      Module libglapi.so.0 with build-id 9331aed5060062bcfafd463d36506312fab59549
                                                      Module libepoxy.so.0 with build-id b6357fc6b748c512f90339433d74502b9d0621dc
                                                      Module libglamoregl.so with build-id fb159cfb9ae1d8541be0d11fd7842ef147857ed7
                                                      Module libnvidia-glcore.so.510.47.03 with build-id e41d11a12fa54ec73f80b2b39fbc7dce9af7de52
                                                      Module libnvidia-tls.so.510.47.03 with build-id 06b381d46fe9a5306b57616a0faece3e7ec0292a
                                                      Module libglxserver_nvidia.so with build-id c96a196edc9f814e1042a7ad5fa3bcbc7385a9c8
                                                      Module libwfb.so with build-id e7f4027f76d37b1d8a37119132fa7e68fbe757ed
                                                      Module libffi.so.8 with build-id f90d8b734f6de9b25faedb8cbfab7054dafc0a42
                                                      Module libstdc++.so.6 with build-id 9b5eeeb149bf3c4efe787fb398b44f00507aec87
                                                      Module libexpat.so.1 with build-id c3b8b6921f5b323540b84acd301ccc7bc5bc0428
                                                      Module libwayland-server.so.0 with build-id 645526447334b85a6f4bf5a8b37737b27696365f
                                                      Module libgbm.so.1 with build-id 5bc03a95f0b36fc100f1d7ca664ebacda793d4c1
                                                      Module modesetting_drv.so with build-id bcc778cae5fde706c881103c56c4768e605464b3
                                                      Module nvidia_drv.so with build-id a925880f5482fcb23dc3757ada68c2d99fc8b074
                                                      Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
                                                      Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
                                                      Module libGLX.so.0 with build-id 2a08836c6e6126ce9ff4496b6aacaf29ae9b4e7b
                                                      Module libGLdispatch.so.0 with build-id 501765b3a78d668860fa54229b18107473aeda4c
                                                      Module libGL.so.1 with build-id 912ac4f37a9fa2d5abcf7a9088c9983cfe46f12a
                                                      Module libglx.so with build-id 6b205eec3a3ff50b171967e2bd104793f92ea0b3
                                                      Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                                                      Module libbrotlicommon.so.1 with build-id a4ba3f4b4571c8272343b621da812a6e24a202a7
                                                      Module libglib-2.0.so.0 with build-id bd949a4794ad959019499c6afcb8f416dcff9810
                                                      Module libgraphite2.so.3 with build-id 47761dc11e553f519cde97ed9ee985be12ccdae2
                                                      Module libresolv.so.2 with build-id c915c72668282861a813f7ea3c0780f37b681dc0
                                                      Module libkeyutils.so.1 with build-id ac405ddd17be10ce538da3211415ee50c8f8df79
                                                      Module libkrb5support.so.0 with build-id adf65240a4d2aba772d7a0772b4d015469934113
                                                      Module libcom_err.so.2 with build-id 1481d614a1c3e3692b1673e8ad35ba41fbea3658
                                                      Module libk5crypto.so.3 with build-id eb8220b8f36675aac769450be4cb6bb7f97ec38a
                                                      Module libkrb5.so.3 with build-id 72d26767c5cb1097db75a5f5bff88860233c902b
                                                      Module libgpg-error.so.0 with build-id 82524ee3d1c4c2244d7cfdcc1e6eea5f9855f6c6
                                                      Module libbrotlidec.so.1 with build-id 45defc036e918e0140a72f1fbce6e7692d38241d
                                                      Module libharfbuzz.so.0 with build-id 8006a225ec61b8231d0b003aebab9920ac0b9179
                                                      Module libpng16.so.16 with build-id 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                                                      Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                                                      Module libgssapi_krb5.so.2 with build-id e6e098ad51ce7bdd3dbe902d7b0f69a90f8a9e08
                                                      Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d234337d835
                                                      Module libgcrypt.so.20 with build-id db45f5d5e0f7af1e77324fea1885f974619ad268
                                                      Module libcap.so.2 with build-id eb6dae97527fc89dbb0d5bb581a15acd02ae9f56
                                                      Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                                      Module libzstd.so.1 with build-id 72f3511cba7db578f6a2647925f35664da6c838b
                                                      Module liblzma.so.5 with build-id 8b615460aa230708c5183f16bede67aa0437d95e
                                                      Module librt.so.1 with build-id 75484da2d6f1515189eefa076e0a40328834cd16
                                                      Module libfreetype.so.6 with build-id 26c5f833068ff72660d1975cbc2074c3eb47fad8
                                                      Module libfontenc.so.1 with build-id 5a11f1fb8c3f2714be9eb6697318f20e301e1d2f
                                                      Module libz.so.1 with build-id 0c1459c56513efd5d53eb3868290e9afee6a6a26
                                                      Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
                                                      Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
                                                      Module libxcvt.so.0 with build-id 30bad674c8227152bb709556a3657d0258554309
                                                      Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
                                                      Module libtirpc.so.3 with build-id 5bef2adfdee3df283f593b3e2d37b6dac405256a
                                                      Module libdrm.so.2 with build-id 457a1a1bd25f1d5541a10d3f16c5dc1440d77c7d
                                                      Module libudev.so.1 with build-id 10425bceda4d2b8dfaa2453dd7e833ea873f88a1
                                                      Module libdbus-1.so.3 with build-id 74f2ab9c60512f3a93c932c3f627564d42e0b11e
                                                      Module libsystemd.so.0 with build-id a83a62063b8098eda274d25251d619f0503bf011
                                                      Module libxshmfence.so.1 with build-id 8876d9ccf620858795724ca24b9e567585a77cec
                                                      Module libXfont2.so.2 with build-id 154202dd7ddb86f6ae4d3bc762dfd8570b86882a
                                                      Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
                                                      Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
                                                      Module libnettle.so.8 with build-id 9a878e513c02007598fcf1e2e286c2203f13536e
                                                      Module libpciaccess.so.0 with build-id 9dd24e76ebc38465541313b36446ffb4af842c12
                                                      Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                                                      Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                                                      Module libpixman-1.so.0 with build-id 341f793dcada3a48a306a793d265a517e3f2e7d6
                                                      Module Xorg with build-id 6f29abbdcaa56942d79296af1598dadcceae59c2
                                                      Stack trace of thread 7699:
                                                      #0  0x00007f45b5398d22 raise (libc.so.6 + 0x3cd22)
                                                      #1  0x00007f45b5382862 abort (libc.so.6 + 0x26862)
                                                      #2  0x000055922add79b0 OsAbort (Xorg + 0x1539b0)
                                                      #3  0x000055922add94f5 FatalError (Xorg + 0x1554f5)
                                                      #4  0x000055922addeeca n/a (Xorg + 0x15aeca)
                                                      #5  0x00007f45b5540870 n/a (libpthread.so.0 + 0x13870)
                                                      
                                                      Stack trace of thread 7713:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7716:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7718:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7715:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7721:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7725:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7720:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7722:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7723:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7714:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)
                                                      #3  0x00007f45aec63aac n/a (radeonsi_dri.so + 0x1d4aac)
                                                      #4  0x00007f45b5536259 start_thread (libpthread.so.0 + 0x9259)
                                                      #5  0x00007f45b545a5e3 __clone (libc.so.6 + 0xfe5e3)
                                                      
                                                      Stack trace of thread 7717:
                                                      #0  0x00007f45b55428ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                      #1  0x00007f45b553c270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                      #2  0x00007f45aec6adfc n/a (radeonsi_dri.so + 0x1dbdfc)

many thanks for explanation of this

**Comment by DaVikingMan** [comment]
Which display manager are you using?

**Comment by nmars-cloud** [comment]
thanks for reply DaVikingMan im using lightdm i tried sddm gdm linux lts kernel nothing works thanks for help

**Comment by DaVikingMan** [comment]
Does removing xorg.conf(/etc/X11/xorg.conf) fix the problem for you?

**Comment by nmars-cloud** [comment]
no not working on optimus manager either thanks gemini for help

**Comment by geminis3** [comment]
Hello there @nmars-cloud ,

Can you send me the output of `lspci` and `xrandr --listproviders` commands when running on hybrid mode?

Greetings.
