### ISSUE TITLE
Can't use x11

### ISSUE THREAD

**Issue by ajfpay** [bayasdev/envycontrol#18]
After switch to hybrid mode, gnome force to wayland, I try disable wayland and can't see panel login anymore

**Comment by ajfpay** [comment]
Gdm down
https://imgur.com/gallery/rtqJXC3

**Comment by ajfpay** [comment]
Specs:
OS: Manjaro
DE: GNOME 
GRAPICH: Intel HD 630 + Nvidia GTX 1060
CPU: i7-7700HQ

**Comment by DaVikingMan** [comment]
Does removing xorg.conf(/etc/X11/xorg.conf) fix the problem?(Reboot after removing the file)

**Comment by ajfpay** [comment]
> 

but I don't have xorg.conf. I try switch integrated work, can use X11 and switch to Nvidia work again with X11. Only on hybrid mode can't  use X11

**Comment by DaVikingMan** [comment]
1. Run `systemctl restart gdm.service` to open the login panel again
2. There should be a gear icon bottom-right of the login screen. Click that and there should be an option called 'Gnome on Xorg' and login

**Comment by DaVikingMan** [comment]
If the above fix didn't work, can you post the output of `cat /proc/cmdline`?

**Comment by ajfpay** [comment]
> If the above fix didn't work, can you post the output of `cat /proc/cmdline`?

after switch to hybrid and reboot, just black screen, I try `systemctl restart gdm.service` on tty, but same problem, just blackscreen again.
output:
`BOOT_IMAGE=/boot/vmlinuz-5.16-x86_64 root=UUID=c5e6cdd6-1917-49e8-bc48-50afcc0549f8 rw quiet udev.log_priority=3 ec_sys.write_support=1`

**Comment by DaVikingMan** [comment]
Follow the instructions mentioned here(https://github.com/geminis3/envycontrol/issues/14#issuecomment-1032801519)

**Comment by DaVikingMan** [comment]
Also, are you using Intel+AMD or Intel+Nvidia?

**Comment by ajfpay** [comment]
> > If the above fix didn't work, can you post the output of `cat /proc/cmdline`?
> 
> after switch to hybrid and reboot, just black screen, I try `systemctl restart gdm.service` on tty, but same problem, just blackscreen again. output: `BOOT_IMAGE=/boot/vmlinuz-5.16-x86_64 root=UUID=c5e6cdd6-1917-49e8-bc48-50afcc0549f8 rw quiet udev.log_priority=3 ec_sys.write_support=1`

still can't, only wayland can use hybrid mode

**Comment by DaVikingMan** [comment]
> Follow the instructions mentioned here([#14 (comment)](https://github.com/geminis3/envycontrol/issues/14#issuecomment-1032801519))

Did the following solution also not fix the problem?

**Comment by ajfpay** [comment]
> > Follow the instructions mentioned here([#14 (comment)](https://github.com/geminis3/envycontrol/issues/14#issuecomment-1032801519))
> 
> Did the following solution also not fix the problem?

yes, after following the method still not fixed, I try to reinstall gnome, try switch xfce same problem, failed to start DE. 
Last I try to uninstall envycontrol and still cant hybrid mode 😫

**Comment by ajfpay** [comment]
only Optimus manager can set hybrid on x11. I don't know what happens on my laptop

**Comment by JoseBritto** [comment]
Hey, I am facing a similar problem. When I switch to hybrid mode I no longer have the ability to switch to Xorg from the gdm login screen and it defaults to wayland. This is doesn't happen in integrated or nvidia mode.

I have `nvidia-drm.modeset=1` set in my boot parameters and `/etc/X11/xorg.conf ` is not present when in hybrid mode.


cat /proc/cmdline:
```
BOOT_IMAGE=/boot/vmlinuz-5.15-x86_64 root=UUID=671c810c-ffb9-439c-9e4a-348b783d4a33 rw resume=UUID=671c810c-ffb9-439c-9e4a-348b783d4a33 resume_offset=4120576 nvidia-drm.modeset=1 udev.log_priority=3 sysrq_always_enabled=1
```
 

System info:
```
OS: Manjaro 64-bit
DE: Gnome 41.3
GPU: Nvidia GTX 1050
CPU: Intel i7-8750H
Kernel: 5.15
```

**Comment by geminis3** [comment]
Interesting, if you remove /etc/modprobe.d/nvidia.conf GDM works as
expected?

I tested on Ubuntu 22.04 and for me both Xorg and Wayland sessions are
available on all modes.

**Comment by JoseBritto** [comment]
> Interesting, if you remove /etc/modprobe.d/nvidia.conf GDM works as
expected?

No GDM still doesn't show xorg as an option.

**Comment by JoseBritto** [comment]
My nvidia driver version is 510.54. Forgot to add that in my first comment.
Also before I installed envycontrol gdm would force me into xorg session with no option to choose wayland on login. I think this was expected behaviour but I'm not sure.

**Comment by bayasdev** [comment]
> My nvidia driver version is 510.54. Forgot to add that in my first comment.
> Also before I installed envycontrol gdm would force me into xorg session with no option to choose wayland on login. I think this was expected behaviour but I'm not sure.

You need to enable nvidia-suspend services (as per README) for Wayland to appear on GDM
