### ISSUE TITLE
switching to nvidia mode prevents X and sddm from starting.

### ISSUE THREAD

**Issue by salperinlea** [bayasdev/envycontrol#20]
Running:
Arch, kernel 5.16.10. 
KDE 5.24.1 with SDDM.
intel tigerlake / nvidia rtx 3060 hybrid.
Of unknown relevance: 4K OLED screen. 

After the reboot when I set it to nvidia mode, attempts to boot arch hang at a blinking white cursor. booting to tty works, at which point I can reverse the change, returning to hybrid mode.

Not sure if there are any logs I can post, but if there are, I'll submit them.

**Comment by DaVikingMan** [comment]
Can you try removing (/etc/X11/xorg.conf) and rebooting as that might fix the problem?

**Comment by salperinlea** [comment]
Doesn't exist -- removed it well before installing envycontrol.

**Comment by DaVikingMan** [comment]
Which init system are you using?

**Comment by salperinlea** [comment]
Systemd. Grub bootloader.On Feb 21, 2022 11:01 AM, DaVikingMan ***@***.***> wrote:
Which init system are you using?

**Comment by DaVikingMan** [comment]
Try running `sudo groupadd -G 33 nvidia_sddm ; usermod -G nvidia_sddm sddm`

**Comment by salperinlea** [comment]
I think you mean to use -g and not -G for groupadd, since -G isn't a recognized option.
That said, GID 33 is already taken on my system -- that's the http group.
Is there a reason you suggested that GID or would any unused integer work?

Noting also: sddm has GID 973, with no members (but, my main user is in wheel, so no issue), and the group video, GID 985, has sddm as a member.

**Comment by geminis3** [comment]
Hello there @salperinlea,

Can you send me the output of `lspci` and `xrandr --listproviders` commands when running on hybrid mode?

Greetings.

**Comment by salperinlea** [comment]
```
lspci
0000:00:00.0 Host bridge: Intel Corporation 11th Gen Core Processor Host Bridge/DRAM Registers (rev 05)
0000:00:01.0 PCI bridge: Intel Corporation 11th Gen Core Processor PCIe Controller #1 (rev 05)
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
0000:00:07.0 PCI bridge: Intel Corporation Tiger Lake-H Thunderbolt 4 PCI Express Root Port #0 (rev 05)
0000:00:07.2 PCI bridge: Intel Corporation Tiger Lake-H Thunderbolt 4 PCI Express Root Port #2 (rev 05)
0000:00:08.0 System peripheral: Intel Corporation GNA Scoring Accelerator module (rev 05)
0000:00:0d.0 USB controller: Intel Corporation Tiger Lake-H Thunderbolt 4 USB Controller (rev 05)
0000:00:0d.2 USB controller: Intel Corporation Tiger Lake-H Thunderbolt 4 NHI #0 (rev 05)
0000:00:0d.3 USB controller: Intel Corporation Tiger Lake-H Thunderbolt 4 NHI #1 (rev 05)
0000:00:0e.0 RAID bus controller: Intel Corporation Volume Management Device NVMe RAID Controller
0000:00:14.0 USB controller: Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller (rev 11)
0000:00:14.2 RAM memory: Intel Corporation Tiger Lake-H Shared SRAM (rev 11)
0000:00:14.3 Network controller: Intel Corporation Tiger Lake PCH CNVi WiFi (rev 11)
0000:00:15.0 Serial bus controller: Intel Corporation Tiger Lake-H Serial IO I2C Controller #0 (rev 11)
0000:00:15.1 Serial bus controller: Intel Corporation Device 43e9 (rev 11)
0000:00:16.0 Communication controller: Intel Corporation Tiger Lake-H Management Engine Interface (rev 11)
0000:00:1d.0 System peripheral: Intel Corporation Device 09ab
0000:00:1d.7 PCI bridge: Intel Corporation Device 43b7 (rev 11)
0000:00:1f.0 ISA bridge: Intel Corporation Tiger Lake-H LPC/eSPI Controller (rev 11)
0000:00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-H HD Audio Controller (rev 11)
0000:00:1f.4 SMBus: Intel Corporation Tiger Lake-H SMBus Controller (rev 11)
0000:00:1f.5 Serial bus controller: Intel Corporation Tiger Lake-H SPI Controller (rev 11)
0000:01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
0000:01:00.1 Audio device: NVIDIA Corporation Device 228e (rev a1)
0000:58:00.0 SD Host controller: Genesys Logic, Inc GL9750 SD Host Controller (rev 01)
10000:e0:1d.0 PCI bridge: Intel Corporation Tiger Lake-H PCI Express Root Port #9 (rev 11)
10000:e1:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM9A1/PM9A3/980PRO

```

```
xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x4b cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 5 outputs: 8 associated providers: 1 name:Intel
Provider 1: id: 0x1ea cap: 0x2, Sink Output crtcs: 4 outputs: 1 associated providers: 1 name:NVIDIA-G0

```
Hope this is useful!

**Comment by geminis3** [comment]
@salperinlea please remove xf86-video-intel package:

`sudo pacman -Rsc xf86-video-intel`

Then switch to Nvidia mode again, thanks!

**Comment by salperinlea** [comment]
Hi @geminis3,
Unfortunately, no change is accomplished by removing xf86-video-intel.

**Comment by kphanipavan** [comment]
https://github.com/geminis3/envycontrol/blob/main/envycontrol.py#L176

Here the program adds `NVIDIA-0` as an output source to the display manager startup script

But @salperinlea 's xrandr provider list contains `NVIDIA-G0`, with a 'G'. Does that make a difference?

I myself am struggling with getting Nvidia GPU working as primary GPU for the past the week. I had NVIDIA-G0 in the provider list as well and adding `G0` worked for me but I didn't test it with just `0`.

Can you see if changing `NVIDIA-0` to `NVIDIA-G0` works??

**Comment by geminis3** [comment]
> https://github.com/geminis3/envycontrol/blob/main/envycontrol.py#L176
> 
> Here the program adds `NVIDIA-0` as an output source to the display manager startup script
> 
> But @salperinlea 's xrandr provider list contains `NVIDIA-G0`, with a 'G'. Does that make a difference?
> 
> I myself am struggling with getting Nvidia GPU working as primary GPU for the past the week. I had NVIDIA-G0 in the provider list as well and adding `G0` worked for me but I didn't test it with just `0`.
> 
> Can you see if changing `NVIDIA-0` to `NVIDIA-G0` works??

`NVIDIA-0` means your dGPU is the output source provider aka primary GPU so there should be something wrong on the generated Xorg config, please send me the output of the `lspci` command,

**Comment by kphanipavan** [comment]
OS: Fedora 36 KDE Spin, Fresh install.
Nvidia Drivers: Installed using https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux

Haven't used EnvyControl yet.
<details>
<summary>My nvidia.conf:</summary>

```bash
#This file is provided by xorg-x11-drv-nvidia
#Do not edit

Section "OutputClass"
        Identifier "nvidia"
        MatchDriver "nvidia-drm"
        Driver "nvidia"
        Option "AllowEmptyInitialConfiguration"
        Option "BaseMosaic" "on"
        Option "PrimaryGPU" "yes"
EndSection

Section "ServerLayout"
        Identifier "layout"
        Option "AllowNVIDIAGPUScreens"
EndSection
```

</details>


<details>
<summary>My /etc/sddm/Xsetup file:</summary>

```bash
#!/usr/bin/sh
# Xsetup - run as root before the login dialog appears
xrandr --setprovideroutputsource modesetting NVIDIA-G0
xrandr --auto
```

</details>

The above setup works for me. The display runs on the Nvidia GPU without any issues.

The 'G' part looked different compared to other online sources, so I thought it might be causing some issue...

<details>
<summary>My System: </summary>

Acer Predator Helios 300 2021
Intel 10th gen i7-10870H
Nvidia RTX 3060 Mobile
FHD Non-Gsync Display

</details>

**Comment by adhamsalama** [comment]
The same happens to me on a fresh Fedora 36 KDE Spin, fresh install.

Copying @kphanipavan's /etc/sddm/Xsetup file solves the issue.

**Comment by joeg1484** [comment]
Just to add to this list... Same with me.. Fresh install of Fedora 37 - nvidia only mode doesnt work on KDE... GDM/Gnome seems to work fine.

**Comment by joeg1484** [comment]
So ... yes, this worked... I had to add G0 for mine as well... However, does the Xsetup file keep those lines in it when I switch to hybrid as well?
