### ISSUE TITLE
Wayland not displaying external monitor but detected by display manager

### ISSUE THREAD

**Issue by gammison** [bayasdev/envycontrol#28]
I'm running arch on a Lenovo y540 laptop. On Wayland, the external monitors are detected when plugged in their respective ports and are visible in the display manager settings but they don't display anything, just a black screen.

Kernel Version: Linux version 5.16.13-arch1-1 (linux@archlinux) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.38) #1 SMP PREEMPT 

Nvidia  Drivers Version: 5.10.54

EnvyControl Version: 1.3-1

Display Manager: GDM

**Comment by geminis3** [comment]
Since your laptop has a MUX try switching to dedicated graphics only on
BIOS and external displays should work (also set EnvyControl to hybrid to
revert any change).

External displays + Wayland is broken on Optimus laptops as of now (Nvidia
driver issue).

**Comment by gammison** [comment]
Thanks. Unfortunately I'm getting that terrible bug where plymouth hangs around starting the host name process. I'm loading the nvidia modules early with mkinitcpio (like so ```
