### ISSUE TITLE
On Xorg, certain Vulkan processes attempt to start on the integrated GPU

### ISSUE THREAD

**Issue by gammison** [bayasdev/envycontrol#29]
Running arch on a Lenovo Y540 laptop. When using Xorg, the nvidia GPU properly runs the display manager and automatically runs all open gl applications. Certain vulkan programs though attempt to start and then black screen. One, the ```vkcube``` demo, stated it was attempting to run on integrated graphics. I had to use ```prime-run``` to force it back to the nvidia gpu at which point it ran fine. It's not clear at all to me how certain processes would attempt to start on the integrated graphics.

Kernel Version: Linux version 5.16.13-arch1-1 (linux@archlinux) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.38) https://github.com/geminis3/envycontrol/pull/1 SMP PREEMPT

Nvidia Drivers Version: 5.10.54

EnvyControl Version: 1.3-1

Display Manager: GDM

**Comment by DaVikingMan** [comment]
What's the output of `glxinfo | grep "OpenGL vendor string"`?

**Comment by gammison** [comment]
It doesn't output anything. I actually reinstalled vulkan tools and have not been able to reproduce the issue.
