### ISSUE TITLE
[QUESTION] What's the proper way to clean remove all envycontrol files?

### ISSUE THREAD

**Issue by Scotty-Trees** [bayasdev/envycontrol#41]
Greetings,

First off, thanks again for making envycontrol. I do a lot of testing from time to time, so I do switch from optimus-manager to envycontrol, but the last time I removed envycontrol I believe it left behind a xorg.conf file or something else, I can't quite remember. There isn't a "How to completely remove envycontrol" README (I think this should be added in the future though), so for those that need to remove it  completely for whatever reason(s) and have no conflicts when they try to install another GPU switch. 

What would be the full, complete way to remove envycontrol and all associated files it has created? I think once this question is answered, it should be added to the main page as well, since sometimes switching to different GPU switching options can cause issues (e.g. going from optimus-manager to envycontrol or vice versa).

**Comment by DaVikingMan** [comment]
The file xorg.conf is created automatically if you run a command(such as nvidia-xconfig) or is manually configured and isn't created by envycontrol(It is also, in some cases recommended to remove this file if you encounter an issue)

**Comment by bayasdev** [comment]
Use `sudo envycontrol --reset`
