### ISSUE TITLE
Stuck at boot while switching to integrated or hybrid mode.

### ISSUE THREAD

**Issue by bhaskarkhoraja** [bayasdev/envycontrol#42]
This issue started from envycontrol V2, whenever i switch to integrated or hybrid i get stuck at boot. I thought it will be fixed but its been a long time. I found that it was removing EXTRA_PATH while switching to integrated or nvidia so i removed it from _cleanup() and was working fine.

From
`to_remove = (BLACKLIST_PATH,UDEV_INTEGRATED_PATH, UDEV_PM_PATH, XORG_PATH, EXTRA_PATH, '/etc/X11/xorg.conf.d/90-nvidia.conf',.......................`

To
`to_remove = (BLACKLIST_PATH,UDEV_INTEGRATED_PATH, UDEV_PM_PATH, XORG_PATH, '/etc/X11/xorg.conf.d/90-nvidia.conf',.......................`

So, is there any problem in my system or other people are facing this problem too.
Hope it will be fixed ASAP.

**Comment by geminis3** [comment]
Please manually remove `/etc/X11/xorg.conf` if exists and all Nvidia related configs inside `/etc/X11/xorg.conf.d/`, the `EXTRA_PATH` is just a file that gets created on Nvidia mode if the user choose to enable Composition Pipeline nor Coolbits.

**Comment by Bhaskar-Khoraja** [comment]
> Please manually remove `/etc/X11/xorg.conf` if exists and all Nvidia related configs inside `/etc/X11/xorg.conf.d/`

I have already removed /etc/X11/xorg.conf and there is no configs related to Nvidia in /etc/X11/xorg.conf.d except for some keyboard and touchpad related config.

**Comment by geminis3** [comment]
Which distro are you using? as well as your iGPU model

**Comment by Bhaskar-Khoraja** [comment]
I am currently on Arch Linux.

The iGPU is Intel UHD 630.

**Comment by DaVikingMan** [comment]
When switching to hybrid, try switching off(press 'n') the RTD3 power management when prompted to enter it.

**Comment by Bhaskar-Khoraja** [comment]
> When switching to hybrid, try switching off(press 'n') the RTD3 power management when prompted to enter it.

Thanks i can now switch between hybrid or integrated without any problem. Dose that mean it don't support RTD3 power management on my system?

**Comment by DaVikingMan** [comment]
It may be that your gpu doesn't support RTD3 management(since you aren't using a turing-gen gpu)

**Comment by ajfpay** [comment]
> > When switching to hybrid, try switching off(press 'n') the RTD3 power management when prompted to enter it.
> 
> Thanks i can now switch between hybrid or integrated without any problem. Dose that mean it don't support RTD3 power management on my system?

can I have file /etc/X11/xorg.conf and nvidia config in folder /etc/X11/xorg.conf.d/?
Same problem, stuck if switch hybrid mode, try to switching off RTD3 power management not work.

Spec: I7-7700HQ
Display: IGPU Intel HD 630 & Nvidia 1060 6GB

Nothing conf xorg.conf on hybrid mode

**Comment by geminis3** [comment]
RTD3 requires Turing or newer card as well as a compatible processor.
