### ISSUE TITLE
Plymouth reports that Nvidia drivers are not available and that the system will fall back to Nouveau when in integrated mode

### ISSUE THREAD

**Issue by jasons393** [bayasdev/envycontrol#44]
Distro: Fedora 36
Kernel: 5.17.8-300.fc36.x86_64 
DM and DE: GDM and Gnome 42
Nvidia version: 510.68.02
EnvyControl version: 2.1.1

As said in the title, Plymouth reports that the proprietary Nvidia drivers and not avaliable and the system will be falling back to Nouveau in integrated mode for EnvyControl. I noticed that in Gnome, there was no "Launch in discrete" options when right-clicking on an application in the app grid. But, I am not sure if Fedora actually loaded Nouveau. I don't see any other issues, though. Hopefully anyone knows what is going on. Also, thank you to the developers for making this program!

**Comment by geminis3** [comment]
Just ignore the warning, last time I tested Fedora neither Nvidia or
nouveau modules were loaded.

You can check it by doing an lsmod ;)

**Comment by ActualDisaster2447** [comment]
Is there a way to remove that warning, though? Like it should be a setting that gets removed/disabled once you switch to Hybrid/Nvidia so that when one wants to remove Envycontrol, it can be done rather cleanly.

**Comment by geminis3** [comment]
That's Fedora / RPMFusion specific, other distros don't show any warning on
integrated mode.

**Comment by ActualDisaster2447** [comment]
> That's Fedora / RPMFusion specific, other distros don't show any warning on
integrated mode.

That is true. Guess we'll have to live with it.

**Comment by jasons393** [comment]
I can confirm that everything works, it is just a warning you can ignore. @geminis3 can you put Fedora 36 in the working distros list?
