### ISSUE TITLE
`systemd-udevd` high CPU usage when `envycontrol -s integrated`

### ISSUE THREAD

**Issue by everyx** [bayasdev/envycontrol#48]
`systemd-udevd` has been using over 90 CPU usage after `envycontrol -s integrated` and reboot, but in `hybrid` mode, it's works fine.

Switching from `integrated` to `hybrid` will prevent the system from rebooting due to high CPU usage by `systemd-udevd`

![图片](https://user-images.githubusercontent.com/1665522/174512997-fe9b9fd1-d2c4-4656-a1a0-567a690b30f7.png)

**Comment by DaVikingMan** [comment]
This seems to be an issue with systemd, try downgrading it
