### ISSUE TITLE
Blinking cursor issue, I have tried the fixes in the "common problems" tab.

### ISSUE THREAD

**Issue by Ghostytriickster** [bayasdev/envycontrol#50]
system info : EndeavourOS on kernel 5.18.9 ; laptop is a GF65 thin 10UE from MSI ; graphic card is an RTX 3060 mobile "max-q".
Currently using Lightdm with Mate.
While removing /etc/X11/xorg.conf Makes the graphical environment go back, it doesn't switch the graphic processor.
there is also no options in my "e" menu of grub saying "quiet splash".
content of the "xorg.conf" file :

```#automatically generated by EnvyControl

Section "ServerLayout"
   Identifier "layout"
   Screen 0 "nvidia"
   Inactive "intel"
EndSection

Screen "Device"
   Identifier "nvidia"
   Driver "nvidia"
   BusID "PCI:1:0:0"

Section "Screen"
   identifier "nvidia"
   Device "nvidia"
   Option "AllowEmptyInitialConfiguration
EndSection

Section "Device"
   Identifier "intel"  
   Driver "modesetting"
EndSection

Section "Screen"
   Identifier "intel"
   Device "intel"
Endsection
```

**Comment by DaVikingMan** [comment]
Can you try removing xorg.conf again and posting the output of nvidia-smi, and checking if systemd-udev is using high cpu(if it is, then this is an systemd issue and I would recommend downgrading systemd and trying again)

**Comment by Ghostytriickster** [comment]
sure thing, though It’ll take some time as I don’t have access to my computer at the moment
