### ISSUE TITLE
nvidia driver wont work after uninstalling envycotnrol

### ISSUE THREAD

**Issue by Bruol** [bayasdev/envycontrol#54]
Thank you for this great project!
I have noticed, that if you switch to integrated graphics and then uninstall envycontrol via `pip uninstall`, the udev rules at `/lib/udev/rules.d/50-remove-nvidia.rules` and the file that blacklists the nvidia driver at `/etc/modprobe.d/blacklist-nvidia.conf` are not deleted. This results in the nvidia driver not working after the uninstall, until you manually delete these files.

**Comment by geminis3** [comment]
> Thank you for this great project!
> I have noticed, that if you switch to integrated graphics and then uninstall envycontrol via `pip uninstall`, the udev rules at `/lib/udev/rules.d/50-remove-nvidia.rules` and the file that blacklists the nvidia driver at `/etc/modprobe.d/blacklist-nvidia.conf` are not deleted. This results in the nvidia driver not working after the uninstall, until you manually delete these files.

Switching to hybrid mode first removes those files ;)
