### ISSUE TITLE
Install Error - Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by InnKeepNY** [bayasdev/envycontrol#58]
Hi all -
On Ubuntu 20.04 LTS which is current and up to date.

When I run 'cd ~/src/envycontrol && sudo pip3 install' I get the following error message:

ERROR: You must give at least one requirement to install (see "pip help install")

and then it quits. I know I'm missing something simple but I keep missing it. 
Thanks in advance!

**Comment by geminis3** [comment]
pip3 install .
