### ISSUE TITLE
Refresh rates are not recognized 

### ISSUE THREAD

**Issue by danielrehsmann** [bayasdev/envycontrol#67]
On my notebook (with hybrid graphics), when I set the graphics mode to Nvidia, I'm not having the choice of my proper screen-refresh rates. However, if I change the graphic chipset in the BIOS, I am able to use 240Hz. 

Adding the screen refresh rates manually over xrandr on X11, as described in (https://wiki.archlinux.org/title/xrandr), gives an error called crtc:0. Manually providing the EDID file, as described here (https://wiki.archlinux.org/title/Kernel_mode_setting#Forcing_modes_and_EDID), does also not help. 

I suppose that this issue is related to the intel drivers since intel restricts the refresh rate to 60Hz. 
I am using Fedora 37 on X11. Any help is much appreciated.

**Comment by cronyakatsuki** [comment]
This is a limitation of using prime syncronization, for example for me with an amd igu and nvidia dgpu my screen is 60hz but xorg think that its a 90hz screen when in nvidia mode.
From what I know its a bug on the nvidia side.
