### ISSUE TITLE
Rebuilds initrd every time I switch

### ISSUE THREAD

**Issue by joeg1484** [bayasdev/envycontrol#69]
Why? optimus-manager can switch between hybrid and NVIDIA with just a logout, not a complete reboot... Is this possible with envycontrol?

**Comment by cronyakatsuki** [comment]
What distribution are you using?

**Comment by joeg1484** [comment]
At the time, I was using Fedora.

**Comment by cronyakatsuki** [comment]
In fedora, and debian based distro's it is required to rebuild initrd for arch system's it isn't.

**Comment by joeg1484** [comment]
Ok thanks for the info!
