### ISSUE TITLE
Problem with I3wm

### ISSUE THREAD

**Issue by hedgeg0d** [bayasdev/envycontrol#74]
Distribution: Arch Linux, Gnome as default DE
Kernel: 6.1.7-zen1-1.1-zen 
Display manger: Xorg, i3wm
NVIDIA Driver Version: 525.78.01
EnvyControl version 2.3

The problem is that i3 does not start in nvidia mode(no ForceCompostionPipeline, Coolbits enabled). I have gdm, where i select i3, and start, but nothing happens - just black, even not turned on screen. Similar problem with dwm. Gnome works just fine with any mode of gpu selected

**Comment by hedgeg0d** [comment]
i3 works in hybrid, by the way

**Comment by bayasdev** [comment]
I'm not sure what's happening on your setup since I mostly use the Gnome DE on Linux, however you can try adding this to your `.xinitrc`:

```
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
```

**Comment by hedgeg0d** [comment]
Unfortunately this did not help

**Comment by hedgeg0d** [comment]
Update. 

`exec_always xrandr --auto` to ~/.config/i3/config
solved my problem. Thanks. Now i am closing the issue
