### ISSUE TITLE
Full fan speed in lockscreen

### ISSUE THREAD

**Issue by tsoernes** [bayasdev/envycontrol#76]
For some reason, when I lock the computer, the fans on my laptop have started to run at full speed.

Fedora KDE 36

Hybrid mode
Intel + Nvidia on Thinkpad X1 Extreme Gen 2

**Comment by bayasdev** [comment]
I don't think this was caused by Envycontrol, have you updated your kernel recently?

Also check if the problem persists after doing `envycontrol --reset`
