### ISSUE TITLE
[Wiki Update] Update the list of "Tested Distros" in the wiki

### ISSUE THREAD

**Issue by tur1ngb0x** [bayasdev/envycontrol#82]
<https://github.com/bayasdev/envycontrol/wiki/Frequently-Asked-Questions#tested-distros>

I can confirm envycontrol works on these distributions (versions, desktop environments)

```
- Arch Linux (GNOME, MATE, Plasma, Xfce)
- Debian 11 (GNOME, Plasma, Xfce)
- ElementaryOS 6.x,7.x (Pantheon)
- EndeavourOS (GNOME, Plasma, Xfce)
- Fedora 36,37 (GNOME, Plasma, Xfce)
- Linux Mint 20,21 (Cinnamon, Xfce)
- Manjaro (GNOME, Plasma, MATE, Xfce)
- MX Linux 21 (Plasma, Xfce)
- Regolith 2.x (i3wm)
- Ubuntu 20.04.x,22.04.x (GNOME, Plasma, XFCE, MATE)
```

**Comment by bayasdev** [comment]
Done, and thank you for your contributions to the project ;)

PD: I will be issuing a new release to the AUR containing your EOS fix in the following hours.
