### ISSUE TITLE
Cannot change mode (Fedora 37 6.1.12)

### ISSUE THREAD

**Issue by Loskoss** [bayasdev/envycontrol#83]
-Nvidia version:- 525
-Wayland
-envycontrol version - 2.3.1
Hey was trying to go to hybrid mode this was the error i came across 
this message over and over again.

`sudo envycontrol -s hybrid
Enable RTD3 Power Management? (y/N): y
Rebuilding initramfs...
cp: cannot stat '/usr/share/asahi-scripts/*': No such file or directory
dracut-install: Failed to find module 'apple_mailbox'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.kTn5QJ/initramfs -N nvidia|nvidia_drm|nvidia-modeset|nvidia-uvm --kerneldir /lib/modules/5.15.55-rt48xm1.0.fc37.x86_64/ -m apple_mailbox nvme_apple pinctrl-apple-gpio macsmc macsmc-rtkit i2c-apple tps6598x apple-dart dwc3 dwc3-of-simple nvmem-apple-efuses phy-apple-atc xhci-pci pcie-apple gpio_macsmc spi-apple spi-hid-apple spi-hid-apple-of rtc-macsmc simple-mfd-spmi spmi-apple-controller nvmem_spmi_mfd apple-dockchannel dockchannel-hid apple-rtkit-helper
cp: cannot stat '/usr/share/asahi-scripts/*': No such file or directory
dracut-install: Failed to find module 'apple_mailbox'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.ymG5pc/initramfs -N nvidia|nvidia_drm|nvidia-modeset|nvidia-uvm --kerneldir /lib/modules/6.0.15-300.fc37.x86_64/ -m apple_mailbox nvme_apple pinctrl-apple-gpio macsmc macsmc-rtkit i2c-apple tps6598x apple-dart dwc3 dwc3-of-simple nvmem-apple-efuses phy-apple-atc xhci-pci pcie-apple gpio_macsmc spi-apple spi-hid-apple spi-hid-apple-of rtc-macsmc simple-mfd-spmi spmi-apple-controller nvmem_spmi_mfd apple-dockchannel dockchannel-hid apple-rtkit-helper

`

**Comment by bayasdev** [comment]
What? Are you running this on a M1 MacBook? 😳

Beside that, the errors you're getting are not related to Envycontrol itself but from the out of the tree kernel modules your system is trying to build when Envycontrol calls the dracut command to regenerate the initramfs.
