### ISSUE TITLE
FileNotFoundError when trying to switch mode

### ISSUE THREAD

**Issue by Strigifowl** [bayasdev/envycontrol#84]
I just updated to the latest version of Envycontrol (2.3.1-1) and now when I try to switch mode I get this error
![Screenshot_20230224_155429](https://user-images.githubusercontent.com/85646183/221209582-823b484f-935e-4216-9960-4d8feae3b6f6.png)
Any idea why or how I can try to fix this?
Edit: Should note that I am using EndeavourOS and have been since before updating

**Comment by bayasdev** [comment]
My bad, this is related to 9c24c74dbf9acdc9fd3619d46328493db1a34698

Will add another check if the system is using dracut before running the command, please downgrade to 2.3 in the meanwhile ;)

**Comment by Strigifowl** [comment]
Alright, thank you for the quick response
