### ISSUE TITLE
KWin freezing in nvidia mode

### ISSUE THREAD

**Issue by MatveyM11** [bayasdev/envycontrol#85]
My laptops model - HP Victus 16, ryzen 5600h+ rtx 3050ti

```system info
inxi -aG                                               ✔  49s   20:32:47  
Graphics:
  Device-1: NVIDIA GA107M [GeForce RTX 3050 Ti Mobile]
    vendor: Hewlett-Packard driver: nvidia v: 525.89.02
    alternate: nouveau,nvidia_drm non-free: 525.xx+
    status: current (as of 2023-02) arch: Ampere code: GAxxx
    process: TSMC n7 (7nm) built: 2020-22 pcie: gen: 1
    speed: 2.5 GT/s lanes: 8 link-max: gen: 4 speed: 16 GT/s
    lanes: 16 ports: active: none empty: HDMI-A-1
    bus-ID: 01:00.0 chip-ID: 10de:25a0 class-ID: 0300
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile
    Series] vendor: Hewlett-Packard driver: amdgpu v: kernel
    arch: GCN-5 code: Vega process: GF 14nm built: 2017-20 pcie:
    gen: 3 speed: 8 GT/s lanes: 16 link-max: gen: 4
    speed: 16 GT/s ports: active: eDP-1 empty: DP-1
    bus-ID: 06:00.0 chip-ID: 1002:1638 class-ID: 0300
    temp: 44.0 C
  Device-3: Luxvisions Innotech HP Wide Vision HD Camera
    type: USB driver: uvcvideo bus-ID: 1-3:2 chip-ID: 30c9:000e
    class-ID: 0e02
  Display: x11 server: X.Org v: 21.1.7 compositor: kwin_x11
    driver: X: loaded: amdgpu,nvidia dri: radeonsi gpu: amdgpu
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 137
    s-size: 355x200mm (13.98x7.87") s-diag: 407mm (16.04")
  Monitor-1: eDP-1 mapped: eDP model: ChiMei InnoLux 0x1609
    built: 2020 res: 1920x1080 hz: 144 dpi: 137 gamma: 1.2
    size: 355x199mm (13.98x7.83") diag: 407mm (16") ratio: 16:9
    modes: max: 1920x1080 min: 640x480
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: AMD Radeon
    Graphics (renoir LLVM 15.0.7 DRM 3.49 6.1.12-arch1-1)
    direct-render: Yes
```

My OS - 

```neofetch
OS: EndeavourOS Linux x86_64 
Kernel: 6.1.12-arch1-1 
Resolution: 1920x1080 
DE: Plasma 5.27.1 
WM: KWin 
```

After I switch into the nvidia mode, after some time KWIN starts to freeze - cannot move pointer, type anything, etc. though programs continue to work in background, sound is playing etc. The same situation is on the external HDMI monitor.

With Optimus manager, in it's GPU mode, I have had no such error.
I've tried to look into the journalctl when freezes were starting, but there was nothing signaling about any errors at the same time.

EnvyControl during my tests was installed both by pip from source and via AUR.

**Comment by bayasdev** [comment]
Can you attach the /etc/X11/xorg.conf file content?

**Comment by MatveyM11** [comment]
> Can you attach the /etc/X11/xorg.conf file content?

I don't have it.

```terminal
/etc/X11  ls                                                    
xinit  xorg.conf.backup  xorg.conf.d  xorg.conf.nvidia-xconfig-original
```

**Comment by bayasdev** [comment]
Is there any error displayed when you run sudo envycontrol -s nvidia?

**Comment by bayasdev** [comment]
Please try the latest version 😉

**Comment by MatveyM11** [comment]
> Please try the latest version wink

Already testing it. But currently I've found nvidia-mode obsolete for my needs. 
USB to HDMI, in my case type c adapters are working perfectly fine in any mode. Even in the integrated mode I can use external monitors.
Thankfully, laptop vendors didn't ruin it and video signal that goes to CPU in any case is routed via CPU, which eliminates problems with physically connected to GPU HDMI port.

**Comment by MatveyM11** [comment]
> Please try the latest version wink

Now I cannot switch into the `nvidia` mode, after reboot it's still staying in the hybrid mode.

Same result with both `sudo envycontrol -s nvidia`  and ` sudo envycontrol -s nvidia --force-comp --coolbits --verbose `.
Into the hybrid mode i switched without specifiyng RTD3, with command `sudo envycontrol -s hybrid`.

```terminal
 sudo envycontrol -s nvidia --force-comp --coolbits --verbose 
INFO: Removed file /etc/X11/xorg.conf.d/10-nvidia.conf
INFO: Removed file /etc/modprobe.d/nvidia.conf
INFO: Restoring Xsetup backup
INFO: Created file /usr/share/sddm/scripts/Xsetup
INFO: Removed file /usr/share/sddm/scripts/Xsetup.bak
INFO: Found Nvidia GPU at 01:00.0
WARNING: Could not find Intel or AMD iGPU
INFO: Created file /etc/modprobe.d/nvidia.conf
INFO: Created file /etc/X11/xorg.conf.d/10-nvidia.conf
INFO: Found sddm Display Manager
INFO: Creating Xsetup backup
INFO: Created file /usr/share/sddm/scripts/Xsetup.bak
INFO: Created file /usr/share/sddm/scripts/Xsetup
INFO: Added execution privilege to file /usr/share/sddm/scripts/Xsetup
dracut: Executing: /usr/bin/dracut --kver=6.2.5-arch1-1 --force
dracut: dracut module 'dash' will not be installed, because command 'dash' could not be found!
dracut: dracut module 'mksh' will not be installed, because command 'mksh' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'dbus-broker' will not be installed, because command 'dbus-broker' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!
dracut: dracut module 'tpm2-tss' will not be installed, because command 'tpm2' could not be found!
dracut: dracut module 'cifs' depends on 'network', which can't be installed
dracut: dracut module 'fcoe' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fcoemon' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fcoeadm' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: dracut module 'nbd' will not be installed, because command 'nbd-client' could not be found!
dracut: dracut module 'nfs' depends on 'network', which can't be installed
dracut: dracut module 'nvmf' will not be installed, because command 'nvme' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'memstrack' will not be installed, because command 'memstrack' could not be found!
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack and procps-ng
dracut: dracut module 'squash' will not be installed, because command 'mksquashfs' could not be found!
dracut: dracut module 'squash' will not be installed, because command 'unsquashfs' could not be found!
dracut: *** Including module: systemd ***
dracut: *** Including module: systemd-initrd ***
dracut: *** Including module: modsign ***
dracut: *** Including module: i18n ***
dracut: *** Including module: btrfs ***
dracut: *** Including module: crypt ***
dracut: *** Including module: dm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 60-persistent-storage-dm.rules
dracut: Skipping udev rule: 55-dm.rules
dracut: *** Including module: dmraid ***
dracut: *** Including module: kernel-modules ***
dracut: *** Including module: kernel-modules-extra ***
dracut: *** Including module: lvm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 56-lvm.rules
dracut: Skipping udev rule: 60-persistent-storage-lvm.rules
dracut: *** Including module: mdraid ***
dracut: Skipping udev rule: 64-md-raid.rules
dracut: *** Including module: multipath ***
dracut: Skipping udev rule: 40-multipath.rules
dracut: *** Including module: nvdimm ***
dracut: *** Including module: qemu ***
dracut: *** Including module: qemu-net ***
dracut: *** Including module: lunmask ***
dracut: *** Including module: resume ***
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: terminfo ***
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: dracut-systemd ***
dracut: *** Including module: usrmount ***
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including module: shutdown ***
dracut: *** Including modules done ***
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done ***
dracut: *** Hardlinking files ***
dracut: Mode:                     real
dracut: Method:                   sha256
dracut: Files:                    2057
dracut: Linked:                   9 files
dracut: Compared:                 0 xattrs
dracut: Compared:                 507 files
dracut: Saved:                    1.42 MiB
dracut: Duration:                 0.016467 seconds
dracut: *** Hardlinking files done ***
dracut: *** Generating early-microcode cpio image ***
dracut: *** Constructing AuthenticAMD.bin ***
dracut: *** Store current command line parameters ***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Creating image file '/boot/initramfs-6.2.5-arch1-1.img' ***
dracut: *** Creating initramfs image file '/boot/initramfs-6.2.5-arch1-1.img' done ***
```

**Comment by bayasdev** [comment]
> > Please try the latest version wink
> 
> Now I cannot switch into the `nvidia` mode, after reboot it's still staying in the hybrid mode.
> 
> Same result with both `sudo envycontrol -s nvidia`  and ` sudo envycontrol -s nvidia --force-comp --coolbits --verbose `.
> Into the hybrid mode i switched without specifiyng RTD3, with command `sudo envycontrol -s hybrid`.
> 
> ```terminal
>  sudo envycontrol -s nvidia --force-comp --coolbits --verbose 
> INFO: Removed file /etc/X11/xorg.conf.d/10-nvidia.conf
> INFO: Removed file /etc/modprobe.d/nvidia.conf
> INFO: Restoring Xsetup backup
> INFO: Created file /usr/share/sddm/scripts/Xsetup
> INFO: Removed file /usr/share/sddm/scripts/Xsetup.bak
> INFO: Found Nvidia GPU at 01:00.0
> WARNING: Could not find Intel or AMD iGPU
> INFO: Created file /etc/modprobe.d/nvidia.conf
> INFO: Created file /etc/X11/xorg.conf.d/10-nvidia.conf
> INFO: Found sddm Display Manager
> INFO: Creating Xsetup backup
> INFO: Created file /usr/share/sddm/scripts/Xsetup.bak
> INFO: Created file /usr/share/sddm/scripts/Xsetup
> INFO: Added execution privilege to file /usr/share/sddm/scripts/Xsetup
> dracut: Executing: /usr/bin/dracut --kver=6.2.5-arch1-1 --force
> dracut: dracut module 'dash' will not be installed, because command 'dash' could not be found!
> dracut: dracut module 'mksh' will not be installed, because command 'mksh' could not be found!
> dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
> dracut: dracut module 'dbus-broker' will not be installed, because command 'dbus-broker' could not be found!
> dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
> dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!
> dracut: dracut module 'tpm2-tss' will not be installed, because command 'tpm2' could not be found!
> dracut: dracut module 'cifs' depends on 'network', which can't be installed
> dracut: dracut module 'fcoe' will not be installed, because command 'dcbtool' could not be found!
> dracut: dracut module 'fcoe' will not be installed, because command 'fipvlan' could not be found!
> dracut: dracut module 'fcoe' will not be installed, because command 'lldpad' could not be found!
> dracut: dracut module 'fcoe' will not be installed, because command 'fcoemon' could not be found!
> dracut: dracut module 'fcoe' will not be installed, because command 'fcoeadm' could not be found!
> dracut: dracut module 'fcoe-uefi' will not be installed, because command 'dcbtool' could not be found!
> dracut: dracut module 'fcoe-uefi' will not be installed, because command 'fipvlan' could not be found!
> dracut: dracut module 'fcoe-uefi' will not be installed, because command 'lldpad' could not be found!
> dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
> dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
> dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
> dracut: dracut module 'nbd' will not be installed, because command 'nbd-client' could not be found!
> dracut: dracut module 'nfs' depends on 'network', which can't be installed
> dracut: dracut module 'nvmf' will not be installed, because command 'nvme' could not be found!
> dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
> dracut: dracut module 'memstrack' will not be installed, because command 'memstrack' could not be found!
> dracut: memstrack is not available
> dracut: If you need to use rd.memdebug>=4, please install memstrack and procps-ng
> dracut: dracut module 'squash' will not be installed, because command 'mksquashfs' could not be found!
> dracut: dracut module 'squash' will not be installed, because command 'unsquashfs' could not be found!
> dracut: *** Including module: systemd ***
> dracut: *** Including module: systemd-initrd ***
> dracut: *** Including module: modsign ***
> dracut: *** Including module: i18n ***
> dracut: *** Including module: btrfs ***
> dracut: *** Including module: crypt ***
> dracut: *** Including module: dm ***
> dracut: Skipping udev rule: 64-device-mapper.rules
> dracut: Skipping udev rule: 60-persistent-storage-dm.rules
> dracut: Skipping udev rule: 55-dm.rules
> dracut: *** Including module: dmraid ***
> dracut: *** Including module: kernel-modules ***
> dracut: *** Including module: kernel-modules-extra ***
> dracut: *** Including module: lvm ***
> dracut: Skipping udev rule: 64-device-mapper.rules
> dracut: Skipping udev rule: 56-lvm.rules
> dracut: Skipping udev rule: 60-persistent-storage-lvm.rules
> dracut: *** Including module: mdraid ***
> dracut: Skipping udev rule: 64-md-raid.rules
> dracut: *** Including module: multipath ***
> dracut: Skipping udev rule: 40-multipath.rules
> dracut: *** Including module: nvdimm ***
> dracut: *** Including module: qemu ***
> dracut: *** Including module: qemu-net ***
> dracut: *** Including module: lunmask ***
> dracut: *** Including module: resume ***
> dracut: *** Including module: rootfs-block ***
> dracut: *** Including module: terminfo ***
> dracut: *** Including module: udev-rules ***
> dracut: Skipping udev rule: 40-redhat.rules
> dracut: Skipping udev rule: 50-firmware.rules
> dracut: Skipping udev rule: 50-udev.rules
> dracut: Skipping udev rule: 91-permissions.rules
> dracut: Skipping udev rule: 80-drivers-modprobe.rules
> dracut: *** Including module: dracut-systemd ***
> dracut: *** Including module: usrmount ***
> dracut: *** Including module: base ***
> dracut: *** Including module: fs-lib ***
> dracut: *** Including module: shutdown ***
> dracut: *** Including modules done ***
> dracut: *** Installing kernel module dependencies ***
> dracut: *** Installing kernel module dependencies done ***
> dracut: *** Resolving executable dependencies ***
> dracut: *** Resolving executable dependencies done ***
> dracut: *** Hardlinking files ***
> dracut: Mode:                     real
> dracut: Method:                   sha256
> dracut: Files:                    2057
> dracut: Linked:                   9 files
> dracut: Compared:                 0 xattrs
> dracut: Compared:                 507 files
> dracut: Saved:                    1.42 MiB
> dracut: Duration:                 0.016467 seconds
> dracut: *** Hardlinking files done ***
> dracut: *** Generating early-microcode cpio image ***
> dracut: *** Constructing AuthenticAMD.bin ***
> dracut: *** Store current command line parameters ***
> dracut: *** Stripping files ***
> dracut: *** Stripping files done ***
> dracut: *** Creating image file '/boot/initramfs-6.2.5-arch1-1.img' ***
> dracut: *** Creating initramfs image file '/boot/initramfs-6.2.5-arch1-1.img' done ***
> ```

Can you post the full output (including the content of the created files)?

**Comment by bayasdev** [comment]
@MatveyM11 post the `lspci` output since EnvyControl relies on its output to detect the iGPU vendor (which is AMD on your system)

I can't narrow down the problem without it

**Comment by MatveyM11** [comment]
> @MatveyM11 post the `lspci` output since EnvyControl relies on its output to detect the iGPU vendor (which is AMD on your system)
> 
> I can't narrow down the problem without it

```lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:01.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 7
01:00.0 VGA compatible controller: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 2291 (rev a1)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 16)
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8852AE 802.11ax PCIe Wireless Network Adapter
04:00.0 SD Host controller: Genesys Logic, Inc GL9750 SD Host Controller (rev 01)
05:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c6)
06:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
06:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
06:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
06:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
06:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor (rev 01)
06:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller
```

**Comment by bayasdev** [comment]
@MatveyM11 please test with 3.0.3 update

**Comment by MatveyM11** [comment]
> @MatveyM11 please test with 3.0.3 update

Now I succesefully switched into the nvidia mode. Nvtop also shows that the rtx 3050ti used as a primary GPU.

But now I need to wait and check is the KWIN freezing problem gone, because sometimes it's was starting severl minutes after load of the new session and sometimes after hours of the flawless usage.

**Comment by bayasdev** [comment]
> > @MatveyM11 please test with 3.0.3 update
> 
> Now I succesefully switched into the nvidia mode. Nvtop also shows that the rtx 3050ti used as a primary GPU.

Good to hear

> But now I need to wait and check is the KWIN freezing problem gone, because sometimes it's was starting severl minutes after load of the new session and sometimes after hours of the flawless usage.

I don't think that problem is related to EnvyControl

**Comment by MatveyM11** [comment]
> > > @MatveyM11 please test with 3.0.3 update
> > 
> > 
> > Now I succesefully switched into the nvidia mode. Nvtop also shows that the rtx 3050ti used as a primary GPU.
> 
> Good to hear
> 
> > But now I need to wait and check is the KWIN freezing problem gone, because sometimes it's was starting severl minutes after load of the new session and sometimes after hours of the flawless usage.
> 
> I don't think that problem is related to EnvyControl

I think the same, for sure it's a kind of a problem with NoVideo aka Nvidia proprietary driver.  Though strange that this problem not occures with OptimusManager.
