### ISSUE TITLE
Envycontrol won't work in a muxless optimus laptop

### ISSUE THREAD

**Issue by Juhayer-Al-Wasif** [bayasdev/envycontrol#86]
I have an HP-Envy laptop that will go blank screen when I switch to Nvidia-only mode in Envycontrol.
Here's Why:
```
 neofetch
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢰⡆⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄  wasif@hpenvylaptop14eb0xxx
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢠⣿⣿⡄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄  
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⣾⣿⣿⣿⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · Archcraft x86_64
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⣷⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · HP ENVY Laptop 14-eb0xxx
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⣿⣿⣷⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · 6.2.1-arch1-1
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢼⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · 56 secs
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣤⣈⠻⢿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · 1132 (pacman)
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣿⣿⣿⣿⣮⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · zsh 5.9
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · 1920x1200
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · bspwm
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄    · Arc-Dark [GTK2/3]
⠄⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⣿⡿⣿⣿⡟⠄⠄⠸⣿⣿⡿⣿⣿⣿⣿⣿⣷⡀⠄⠄⠄⠄⠄⠄⠄⠄    · Arc-Circle [GTK2/3]
⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⣿⡏⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⣿⣿⣿⣿⣿⣷⡀⠄⠄⠄⠄⠄⠄⠄    · alacritty
⠄⠄⠄⠄⠄⠄⢀⣼⣿⣿⣿⣿⣿⣿⡗⠄⠄⠄⢀⣠⣤⣀⠄⠄⠄⠸⣿⣿⣿⣿⣿⣿⣷⡀⠄⠄⠄⠄⠄⠄    · 11th Gen Intel i5-1135G7 (8) @ 4.200GHz
⠄⠄⠄⠄⠄⢀⣾⣿⣿⣿⣿⣿⡏⠁⠄⠄⠄⢠⣿⣿⣿⣿⡇⠄⠄⠄⠄⢙⣿⣿⣻⠿⣿⣷⡀⠄⠄⠄⠄⠄    · NVIDIA GeForce GTX 1650 Ti Mobile
⠄⠄⠄⠄⢀⣾⣿⣿⣿⣿⣿⣿⣷⣤⡀⠄⠄⠄⠻⣿⣿⡿⠃⠄⠄⠄⢀⣼⣿⣿⣿⣿⣦⣌⠙⠄⠄⠄⠄⠄    · Intel TigerLake-LP GT2 [Iris Xe Graphics]
⠄⠄⠄⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠄⠄⠄    · 734MiB / 15749MiB
⠄⠄⢠⣿⣿⣿⣿⣿⣿⣿⡿⠟⠋⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⡄⠄⠄
⠄⣠⣿⣿⣿⣿⠿⠛⠋⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠙⠻⢿⣿⣿⣿⣿⣆⠄
⡰⠟⠛⠉⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠙⠛⠿⢆

```
```
lspci
0000:00:00.0 Host bridge: Intel Corporation 11th Gen Core Processor Host Bridge/DRAM Registers (rev 01)
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
0000:00:06.0 PCI bridge: Intel Corporation 11th Gen Core Processor PCIe Controller (rev 01)
0000:00:07.0 PCI bridge: Intel Corporation Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #0 (rev 01)
0000:00:08.0 System peripheral: Intel Corporation GNA Scoring Accelerator module (rev 01)
0000:00:0d.0 USB controller: Intel Corporation Tiger Lake-LP Thunderbolt 4 USB Controller (rev 01)
0000:00:0d.2 USB controller: Intel Corporation Tiger Lake-LP Thunderbolt 4 NHI #0 (rev 01)
0000:00:0e.0 RAID bus controller: Intel Corporation Volume Management Device NVMe RAID Controller
0000:00:14.0 USB controller: Intel Corporation Tiger Lake-LP USB 3.2 Gen 2x1 xHCI Host Controller (rev 20)
0000:00:14.2 RAM memory: Intel Corporation Tiger Lake-LP Shared SRAM (rev 20)
0000:00:14.3 Network controller: Intel Corporation Wi-Fi 6 AX201 (rev 20)
0000:00:15.0 Serial bus controller: Intel Corporation Tiger Lake-LP Serial IO I2C Controller #0 (rev 20)
0000:00:15.1 Serial bus controller: Intel Corporation Tiger Lake-LP Serial IO I2C Controller #1 (rev 20)
0000:00:16.0 Communication controller: Intel Corporation Tiger Lake-LP Management Engine Interface (rev 20)
0000:00:1c.0 PCI bridge: Intel Corporation Device a0be (rev 20)
0000:00:1d.0 System peripheral: Intel Corporation RST VMD Managed Controller
0000:00:1e.0 Communication controller: Intel Corporation Tiger Lake-LP Serial IO UART Controller #0 (rev 20)
0000:00:1e.3 Serial bus controller: Intel Corporation Tiger Lake-LP Serial IO SPI Controller #1 (rev 20)
0000:00:1f.0 ISA bridge: Intel Corporation Tiger Lake-LP LPC Controller (rev 20)
0000:00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)
0000:00:1f.4 SMBus: Intel Corporation Tiger Lake-LP SMBus Controller (rev 20)
0000:00:1f.5 Serial bus controller: Intel Corporation Tiger Lake-LP SPI Controller (rev 20)
0000:01:00.0 3D controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] (rev a1)
0000:2c:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
10000:e0:1d.0 PCI bridge: Intel Corporation Tiger Lake-LP PCI Express Root Port #9 (rev 20)
10000:e1:00.0 Non-Volatile memory controller: Toshiba Corporation XG6 NVMe SSD Controller
```

A muxless Nvidia Optimus laptop is a laptop that has both an integrated GPU (usually Intel) and a discrete GPU (Nvidia) but does not have a hardware multiplexer (mux) to switch between them. Instead, the integrated GPU drives the internal display create the discrete GPU can only be used for rendering tasks.

This means that the X server (the graphical interface for Linux systems) should not be configured to use the Nvidia X driver after installing it, as this would cause conflicts and errors. Instead, users can use tools like Bumblebee or PRIME to manage which applications use the discrete GPU.

Some laptops have a mux that allows switching between integrated and discrete GPUs, but this requires rebooting or logging out. Some laptops also have an additional mux chip added by the manufacturer that can switch between GPUs without rebooting. However, these are not standard features and are not supported by Nvidia.

**Source**: 
(1) Chapter 17. Using the NVIDIA Driver with Optimus Laptops. https://download.nvidia.com/XFree86/Linux-x86_64/455.28/README/optimus.html 

(2) Chapter 17. Using the NVIDIA Driver with Optimus Laptops. https://download.nvidia.com/XFree86/Linux-x86_64/455.28/README/optimus.html 

(3) How to know if the laptop is MUXed or MUXless: r/VFIO - Reddit. https://www.reddit.com/r/VFIO/comments/j64vkx/how_to_know_if_laptop_is_muxed_or_muxless/ 

(4) Chapter 17. Using the NVIDIA Driver with Optimus Laptops. https://download.nvidia.com/XFree86/Linux-x86/384.59/README/optimus.html 

(5) [GUIDE] Optimus laptop dGPU passthrough · GitHub - Gist. https://gist.github.com/Misairu-G/616f7b2756c488148b7309addc940b28 

(6) Intel and NVIDIA GPU Passthrough on an Optimus MUXless Laptop. https://lantian.pub/en/article/modify-computer/laptop-intel-nvidia-optimus-passthrough.lantian/

**Comment by bayasdev** [comment]
Hello there, Envycontrol should work fine despite your laptop doesn't have any video output wired to the dGPU (that's why lspci identifies it as a 3D controller instead of VGA).

I can see you're using bspwm so you need to manually setup your display manager or whatever else to run the following commands at startup:

https://github.com/bayasdev/envycontrol/wiki/Frequently-Asked-Questions#what-to-do-if-my-display-manager-is-not-supported

Doing that will fix your black screen problem on Nvidia mode.

**Comment by Juhayer-Al-Wasif** [comment]
Not only bspwm but also I've tried it in Manjaro KDE, seems like for my device the only solution is Prime render offload and Bumblebee Switch.

**Comment by bayasdev** [comment]
> Not only bspwm but also I've tried it in Manjaro KDE, seems like for my device the only solution is Prime render offload and Bumblebee Switch.

That's an interesting case, what does the `xrandr --listproviders` command outputs?

**Comment by Juhayer-Al-Wasif** [comment]
`Providers: number : 0`

**Comment by bayasdev** [comment]
@Juhayer-Al-Wasif can you try the latest changes from the rewrite-pci branch?

Thank you!

**Comment by Juhayer-Al-Wasif** [comment]
do I just have to install the latest release?

**Comment by bayasdev** [comment]
> do I just have to install the latest release?

No, please clone the repository and run the following commands:

```
git checkout rewrite-pci
sudo python ./envycontrol.py -s nvidia
```

**Comment by bayasdev** [comment]
@Juhayer-Al-Wasif if you have problems following the steps, here's the [link](https://github.com/bayasdev/envycontrol/blob/rewrite-pci/envycontrol.py) to the updated file.

Download and run it from your terminal.

**Comment by gaming128** [comment]
this is odd, i also use a muxless laptop (HP victus 16z-e000) but this problem has never occurred to me, yeah it doesnt magically give my laptop a switch and disable the igpu entirely, but for the most part my dgpu is used more often than my igpu

**Comment by bayasdev** [comment]
> this is odd, i also use a muxless laptop (HP victus 16z-e000) but this problem has never occurred to me, yeah it doesnt magically give my laptop a switch and disable the igpu entirely, but for the most part my dgpu is used more often than my igpu

Can you try the latest changes from the rewrite-pci branch?

PD: I'm prepping for version 3.0 and need testers 😉

**Comment by bayasdev** [comment]
Should be fixed on version 3

**Comment by Juhayer-Al-Wasif** [comment]
Hey, 👋

I am trying the new version still it doesn't work on my laptop when switched to Nvidia only mode

**Comment by bayasdev** [comment]
@Juhayer-Al-Wasif when the problem occurs open a TTY and capture the X.org logs from `/var/log/Xorg.0.log`

**Comment by bayasdev** [comment]
@Juhayer-Al-Wasif do you have `xrandr` installed on your system?

**Comment by Juhayer-Al-Wasif** [comment]
yes

**Comment by Juhayer-Al-Wasif** [comment]
The Nvidia mode now works properly if I setup blacklist nouveau in grub bootloader. this was issue

**Comment by Juhayer-Al-Wasif** [comment]
The Nvidia mode now works properly if I setup blacklist nouveau in grub bootloader. this was issue.
 But then suspend mode doesn't work😳 on manjaro gnome, neither in Endeavor os XFCE

**Comment by Juhayer-Al-Wasif** [comment]
https://user-images.githubusercontent.com/124311164/226940125-82509472-d74f-4b21-a469-34c13e5741cf.mp4


when the laptop goes into suspend mode I can't even enter into tty mode, the screen is completely off. It won't turn on until I reboot forcefully.

**Comment by bayasdev** [comment]
@Juhayer-Al-Wasif have you enabled the nvidia-suspend services according to the README?

**Comment by Juhayer-Al-Wasif** [comment]
I might be missing it, a link would be helpful 🙏

**Comment by bayasdev** [comment]
@Juhayer-Al-Wasif
```
sudo systemctl enable nvidia-{suspend,resume,hibernate}
```

**Comment by Juhayer-Al-Wasif** [comment]
https://user-images.githubusercontent.com/124311164/227105784-d1e77f8f-777b-49a5-ab93-161e9f1682c6.mp4

After suspend, running Nvidia mode the screen is completely stuck and I can't even enter into tty mode.

**Comment by Juhayer-Al-Wasif** [comment]
~~https://user-images.githubusercontent.com/124311164/227105784-d1e77f8f-777b-49a5-ab93-161e9f1682c6.mp4

After suspend, running Nvidia mode the screen is completely stuck and I can't even enter into tty mode. ~~

**Comment by Juhayer-Al-Wasif** [comment]
```
NVreg_PreserveVideoMemoryAllocations
```

This kernel parameter fixed the issue even in manjaro xwayland.

 Thank you @bayasdev
