### ISSUE TITLE
[Suggestion] Enable Nouveau for integrated or hybrid mode?

### ISSUE THREAD

**Issue by ws-volans** [bayasdev/envycontrol#87]
Hi,

and first of all a big thanks for envycontrol, it's just awesome! 

On my laptop, power management works with Nouveau, but of course the performance is sad. It is however much better than with only my integrated GPU. So, would it somehow be possible to have:
- integrated + nouveau (this achieves, with no load, the same power draw than with only integrated, but better performance)
-  Nvidia for when performance is really required

Or do you have any tips how this could be modified? The big plus here would be to have a "low performance" dGPU with working power management for every day use (Nouveau, which is still better than only iGPU), and a "high performance" dGPU when needed (Nvidia, but with no power management).

**Comment by bayasdev** [comment]
A hybrid-nouveau mode could be created, right now I'm a bit busy but feel
free to implement it in the meanwhile and open a PR ;)

**Comment by bayasdev** [comment]
Not feasible since most distros blacklist nouveau once the propietary drivers are installed and I don't want to mantain distro specific quirks.
