### ISSUE TITLE
[QUESTION] global installation after pip install is disabled?

### ISSUE THREAD

**Issue by nrbeaton** [bayasdev/envycontrol#93]
See here:

https://www.linuxuprising.com/2023/03/next-debianubuntu-releases-will-likely.html

It is likely that Debian and Ubuntu (and maybe Fedora) will soon disable `pip install`. How will this affect global installations of envycontrol?

**Comment by bayasdev** [comment]
+1

I'll try to provide a .deb package soon™️

**Comment by sunwire** [comment]
Fedora rpm package is available in COPR repository https://copr.fedorainfracloud.org/coprs/sunwire/envycontrol/

**Comment by bayasdev** [comment]
@sunwire thank you, added to README

**Comment by bayasdev** [comment]
@nrbeaton please test the .deb attached on latest release
https://github.com/bayasdev/envycontrol/releases/download/v3.2.0/python3-envycontrol_3.2.0-1_all.deb

**Comment by nrbeaton** [comment]
@bayasdev sorry I don't have a .deb based system to install on right now (and in the past `prime-select` on Ubuntu has worked fine for me). As for Fedora, I didn't know about the COPR package but I'll test that shortly.
